#define CONTROLE_MILIEU_SERVO 1260 // 1330 -> droite // 1165 -> gauche

#define CONTROLE_INCERTITUDE_PALIER 40 // 30 à la coupe

#define CONTROLE_DIFFERENCE_POS_MAX 30

#define MOTEUR_KP 40
#define MOTEUR_KD 0
#define MOTEUR_KI 10

#define CONTROLE_KP 5
#define CONTROLE_KD 0
#define CONTROLE_KI 0

#define LARGEUR_LIGNE 15
#define DELTA_LARGEUR_LIGNE 8

#define DERIVEE_MIN 5
#define DIFFERENCE_DERIVEES 5

#define ARRET_SEUIL 90
#define ARRET_NB_PICS 4
#define ARRET_MIN_AMPLITUDE 15
#define ARRET_NB_CONSECUTIFS 1

#define COMPTEUR_AVANT_ARRIVEE 3000

//#define DEBUG_LIGNE
//#define DEBUG_ARRET