#define CONTROLE_MILIEU_SERVO 1165

#define CONTROLE_INCERTITUDE_PALIER 30

#define CONTROLE_DIFFERENCE_POS_MAX 30

#define MOTEUR_KP 40
#define MOTEUR_KD 0
#define MOTEUR_KI 10

#define CONTROLE_KP 7
#define CONTROLE_KD 0
#define CONTROLE_KI 0

#define LARGEUR_LIGNE 15
#define DELTA_LARGEUR_LIGNE 8

#define DERIVEE_MIN 5
#define DIFFERENCE_DERIVEES 5
