

#define CONTROLE_INCERTITUDE_PALIER 50 // 30 à la coupe

#define CONTROLE_DIFFERENCE_POS_MAX 30

#define MOTEUR_KP 10
#define MOTEUR_KD 0
#define MOTEUR_KI 0.1
#define MAX_MOTEUR 90


#define LARGEUR_LIGNE 15
#define DELTA_LARGEUR_LIGNE 8

#define DERIVEE_MIN 5
#define DIFFERENCE_DERIVEES 5

#define ARRET_SEUIL 90
#define ARRET_NB_PICS 4
#define ARRET_MIN_AMPLITUDE 15
#define ARRET_NB_CONSECUTIFS 1

#define COMPTEUR_AVANT_ARRIVEE 3000

// revoir ces valeurs
#define AMPLITUDE_SERVO 550
#define POS_MILIEU_SERVO 2400

#define CONTROLE_MILIEU_SERVO 1330 // 1165 -> gauche  /// euh, what?

#define CONTROLE_KP 5
#define CONTROLE_KD 0
#define CONTROLE_KI 0


#define TICS_BY_METER 250
#define METER_BY_TICS 0.004

#define DENOMINATEUR_A 174762.7 // = (2/3)* 64^3
#define DENOMINAT_A_DIVIDE 0.000005722